name: website_proj_1
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  flutter_staggered_animations: ^1.1.1
  flutter_email_sender: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/
    - assets/skills/
    - assets/downloadables/hdh_resume.pdf
